# Site settings
title: Madison Labs
email: info@madisonlabs.io
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "madisonlabs.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
